### ISSUE TITLE
Provide a quick link to the standard vocabulary documentation and possibly standardized queries

### ISSUE THREAD

**Issue by rkboyce** [OHDSI/Hermes#10]
As a user, when using Hermes for exploring a concept, I might like to review the definition/specification for a concept domain or relationship. Would it make sense to provide a quick link to the standard vocabulary documentation? Could be even just a link to an HTML version of the current documents. 

Along those lines, it might be very helpful to provide some link in the results table to community-developed queries that use the specific concepts/concept domains/concept relationships present in the results. This latter enhancement would require some thought on how to identify the relevant queries and present them to users. However, I could see it being helpful for getting folks to edit and add to the queries themselves.

**Comment by fdefalco** [comment]
Any chance this type of information is made available through the knowledge base API? Similar in the way we plan to provide concept frequency information through the Achilles API I could see doing the same with the KB API.

**Comment by fdefalco** [comment]
Which API?
