### ISSUE TITLE
list the version of the vocabulary that HERMES is displaying on the UI somewhere

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Hermes#20]
We can identify the version by querying:  "SELECT VOCABULARY_VERSION FROM VOCABULARY WHERE VOCABULARY_ID = 'None'"    It'd be good to display this somewhere so we know what we're looking into.

**Comment by chrisknoll** [comment]
This is visible in the settings dropdown button, I'm assuming you mean to have it displayed persistently.  Any suggestions on where this should be? Header or footer?

**Comment by pbr6cornell** [comment]
Ah, ok, the drop down under settings is probably sufficient.
